### ISSUE TITLE
0.0.2 release tracker

### ISSUE THREAD

**Issue by fanminshi** [coreos/jetcd#288]
- [x] disable some pkg that blocks 0.0.2 release: https://github.com/coreos/jetcd/pull/287 
- [x] bump version to 0.0.2 ref: https://github.com/coreos/jetcd/pull/289
- [x] sign and release 0.0.2 jar to maven central
- [x] update version to 0.1.0-Snapshot https://github.com/coreos/jetcd/pull/293
- [x] update release page to include what changed for for 0.0.2 release. ref: https://github.com/coreos/jetcd/pull/294
- [x] update readme.md to include 0.0.2 release.

**Comment by fanminshi** [comment]
useful link: http://central.sonatype.org/pages/apache-maven.html

**Comment by fanminshi** [comment]
jetcd v0.0.2 is uploade to maven central.
